FROM node:17.9.0 AS build

WORKDIR /app

ARG TG_TOKEN
ARG VM_HOST
ARG BACKEND_PORT
ARG NODE_ENV
ARG AVAILABLE_USERS
ARG QUEUE_NAME
ARG AMQP_HOST

ENV TG_TOKEN=$TG_TOKEN
ENV VM_HOST=$VM_HOST
ENV BACKEND_PORT=$BACKEND_PORT
ENV NODE_ENV=$NODE_ENV
ENV AVAILABLE_USERS=$AVAILABLE_USERS
ENV QUEUE_NAME=$QUEUE_NAME
ENV AMQP_HOST=$AMQP_HOST

COPY .. .

RUN npm ci
RUN npm install pm2 -g

CMD ["pm2-runtime", "start", "ecosystem.config.json"]
